build: update Gradle wrapper to version 8.14.3 and comment out Detekt steps in CI configuration

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -20,17 +20,17 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
-      - name: Detekt Code Style
-        continue-on-error: true
-        run: ./gradlew clean detekt
-
-      - name: Upload SARIF to Github using the upload-sarif action
-        continue-on-error: true
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ github.workspace }}/app/build/reports/detekt/detekt.sarif
-          checkout_path: ${{ github.workspace }}
+#      - name: Detekt Code Style
+#        continue-on-error: true
+#        run: ./gradlew clean detekt
+#
+#      - name: Upload SARIF to Github using the upload-sarif action
+#        continue-on-error: true
+#        uses: github/codeql-action/upload-sarif@v3
+#        if: success() || failure()
+#        with:
+#          sarif_file: ${{ github.workspace }}/app/build/reports/detekt/detekt.sarif
+#          checkout_path: ${{ github.workspace }}
 
       - name: Build with Gradle
         run: ./gradlew assembleRelease -PisPublish=true
